apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-cache-status
  namespace: fint-core
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-core-cache-status:latest
  onePassword:
    itemPath: "vaults/aks-beta-vault/items/fint-core-cache-status"
  observability:
    metrics:
      enabled: true
      port: "8080"
      path: /actuator/prometheus