spring:
  security:
    oauth2:
      client:
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            scope: fint-client
            provider: fint-provider
        provider:
          fint-provider:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token

fint:
  components:
    - felles/kodeverk

    - arkiv/noark
    - arkiv/personal
    - arkiv/kodeverk
    - arkiv/samferdsel
    - arkiv/kulturminnevern

    - utdanning/elev
    - utdanning/timeplan
    - utdanning/kodeverk
    - utdanning/vurdering
    - utdanning/utdanningsprogram

    - administrasjon/fullmakt
    - administrasjon/kodeverk
    - administrasjon/personal
    - administrasjon/organisasjon

  security:
    oauth2:
      client:
        username:
        password:

management:
  endpoints:
    web:
      exposure:
        include: prometheus